# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        exclude: ^misc/
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^tests/test_data/sample_items.yaml
      - id: debug-statements
        exclude: syncall/pdb_cli_utils.py
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/lycheeverse/lychee.git
    rev: v0.15.1
    hooks:
      - id: lychee-docker
        # Optionally include additional CLI arguments
        # args: ["--no-progress", "--exclude", "file://"]
        types: [markdown]
  - repo: https://github.com/markdownlint/markdownlint
    rev: "v0.12.0"
    hooks:
      - id: markdownlint
        exclude: ^.github/
        entry: mdl -r ~MD033,~MD013,~MD034,~MD029,~MD007
  - repo: local
    hooks:
      - id: check-github-workflows
        name: Validate GitHub Workflows
        description: "Validate GitHub Workflows against the schema provided by SchemaStore"
        entry: check-jsonschema --builtin-schema vendor.github-workflows
        language: python
        files: ^\.github/workflows/
        types: [yaml]
      - id: black
        name: Black formatter
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: system
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

      - id: pyupgrade
        name: Pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        args: ["--py38-plus"]
        types_or: [python]
        language: system

      # - id: mypy
      #   name: Mypy check
      #   entry: mypy
      #   language: system
      #   pass_filenames: true
      #   types_or: [python, pyi]
      # - id: pyright
      #   name: Pyright check
      #   entry: pyright
      #   language: system
      #   pass_filenames: true
      #   types_or: [python, pyi]
      # - id: Pylint check
      #   name: pylint
      #   entry: pylint
      #   language: system
      #   pass_filenames: true
      #   types: [python]
      #   exclude: ^tests/

      - id: ruff
        name: Ruff Linter
        entry: ruff
        args: ["check", "--fix"]
        language: system
        types_or: [python, pyi]

      - id: poetry-check
        name: Poetry check
        entry: poetry check
        language: system
        pass_filenames: false
        files: "pyproject.toml|poetry.lock"

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
